habit_info = ('Coding', True, 7, 1.5)   
print(habit_info)
weekly_habits = (0, 0, 0, 1, 1, 0, 1, 1, 0, 1)
print(weekly_habits)
print("Habit tracked for", len(weekly_habits), "days.")
print("Completion Of Coding For Day 2 (1 = yes, 0 = no):", weekly_habits[2])
print("Completion Of Coding For Day 8 (1 = yes, 0 = no):", weekly_habits[8])
print("Completion Of Coding For Weekdays (1 = yes, 0 = no):", weekly_habits[0:5])
print("Completion Of Coding For Weekends (1 = yes, 0 = no):", weekly_habits[5:7])
weekly_habits = weekly_habits + (1,)
print("Progress After Adding Another Day:", weekly_habits)
completed = weekly_habits.count(1)
missed = weekly_habits.count(0)
print("Completed Days:", completed)
print("Missed Days:", missed)