inclusive_tuple = (1,1.5, "Tuple", True)
print(inclusive_tuple)
number_tuple = (1,1.5,2,2.5)
print(number_tuple)
add_tuple = (1,2,3,4,5)
print(add_tuple)
add_tuple = add_tuple + (6,)
print(add_tuple)
count_tuple = (1,2,3,1,4,5,1)
print(count_tuple)
print("There are", count_tuple.count(1), "ones in the tuple.")
slice_tuple = (1,2,3,4,5,6,7,8,9,10)
print(slice_tuple)
print(slice_tuple[0:5])

